tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: TEAM_DATA_ENGINEERING
      database: ASAPP_DEV
      schema: RSHINDE_DEV
      warehouse: ASAPP_DEV
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: TEAM_DATA_ENGINEERING
      database: ASAPP_DEV
      schema: RSHINDE_PROD
      warehouse: ASAPP_DEV